### ISSUE TITLE
Episode 06 - The List Returns

### ISSUE THREAD

**Issue by nvk** [nvk/bitcoin.review.episodes#10]

**Comment by nvk** [comment]
Fedmint update https://blog.blockstream.com/fedimint-update/

**Comment by nvk** [comment]
BIPBounty: Tax Deductible Bug Bounties for Bitcoin https://www.nobsbitcoin.com/bipbounty-tax-deductible-bug-bounties-for-bitcoin/

**Comment by justinmoon** [comment]
Fedimint grant season! https://twitter.com/spiralbtc/status/1562474336006524929?s=20

Tether doesn't censor Tornado Cash addresses https://twitter.com/Tether_to/status/1562468486886346753

Tadge joins Lightspark https://twitter.com/tdryja/status/1562485123240456193

**Comment by callebtc** [comment]
Core Lightning v0.12.0 https://blog.blockstream.com/core-lightning-v0-12-0/

`bookkeeper` – bookeeping "data warehouse and business intelligence plugin" with a bunch of cool RPCs. For example, can show income per channel.

`commando` – API interface for CLN with runes for authentication/permission for controlling your node over Lightning TLV messages. Afaik, all the stuff is working on (example: https://github.com/jb55/lnsocket) uses this, now it's part of the main branch. 
`chanbackup` – as far as I got it, something similar to static channel backups in LND

**Comment by relativisticelectron** [comment]
Specter Desktop 1.12.0  https://github.com/cryptoadvance/specter-desktop/commit/7e693367531ca0f4f44d167ddbca385fd114e1fa

**Comment by justinmoon** [comment]
@nvk now there is a lightning accelerator so you can find some funding for all your great ideas https://bitcoinmagazine.com/business/nydig-announces-lightning-accelerator-project

**Comment by nvk** [comment]
Joinmarket v0.9.7 Released

**Comment by nvk** [comment]
Tether not censoring tornado cash https://www.washingtonpost.com/business/2022/08/24/crypto-sanctions-tether/

**Comment by nvk** [comment]
Give @Nobullshitbitcoin a shout out

**Comment by nvk** [comment]
https://github.com/Coldcard/firmware/pull/139#event-7278144457 More CKBUNKER features

**Comment by nvk** [comment]
NPM package (typescript) for SeedXOR. https://github.com/AndreasGassmann/seed-xor

**Comment by nvk** [comment]
robosats on umbrel https://twitter.com/RoboSats/status/1564892599881814016?s=20&t=Bqg3vjdpRismtSmRK4GUHQ

**Comment by nvk** [comment]
Fulcrum added to bitcoinbinary https://github.com/coinkite/bitcoinbinary.org/pull/51#issue-1362514154

**Comment by nvk** [comment]
Ledger adding miniscript soon

**Comment by nvk** [comment]
Wassabi+Trezor

**Comment by nvk** [comment]
moving this to the PR discussion https://github.com/nvk/bitcoin.review.episodes/pulls
