### ISSUE TITLE
EP7

### ISSUE THREAD

**Issue by nvk** [nvk/bitcoin.review.episodes#16]

**Comment by nvk** [comment]
fully Noded https://twitter.com/fullynoded/status/1572380937161244672?s=21&t=

**Comment by relativisticelectron** [comment]
Specter Desktop 1.13.0:  https://github.com/cryptoadvance/specter-desktop/pull/1896/files

**Comment by jonnymarshall** [comment]
### From email:

#### Project Updates
[Hexa moving away from seedless to seed word backup.
](https://twitter.com/HexaWallet/status/1572594775391629313?s=20&t=su9CZlIwOdJdXJ2uxZIig)

#### Noteworthy:
[The Guatemalan Lake Town Mining Bitcoin With Used Cooking Oil](https://www.nobsbitcoin.com/guatemalan-mining-cooking-oil/)

**Comment by jonnymarshall** [comment]
[Peach ](https://www.peachbitcoin.com/)
P2P Mobile application that connects Bitcoin Buyers & Sellers.

**Comment by jonnymarshall** [comment]
[Nunchuk](https://twitter.com/nunchuk_io/status/1574977342698496000?s=11&t=rl5efRxjvFPHgplc5SdEzQ)
 
[@COLDCARDwallet](https://twitter.com/COLDCARDwallet)
 NFC support (demo below)
* Replace-by-fee (RBF) ported to mobile
* BIP21 & Krux QR support
* New "Quick Send" shortcut
* Signing using airgapped keys in collab wallets
* Copy-to-clipboard for addresses & TXIDs
* Perf improvements

**Comment by jonnymarshall** [comment]
[Electrum 4.3.2](https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES)

 * When creating new requests, reuse addresses of expired requests
 * Index requests by ID instead of receiving address. This affects the
   following commands: get_request, get_invoice, list_requests,
   list_invoices, delete_request, delete_invoice
 * Trampoline routing: remember routes that have failed. Try other
   routes instead of systematically raising tampoline fees
 * Fix sweep to_local output from channel backup (#7959)
 * Harden build script for macOS binary: avoid using
   precompiled wheels from PyPI for most packages (#7918)
 * The Windows/AppImage/Android binaries are now built on debian using
   the snapshot.debian.org archive instead of ubuntu. This should help
   with historical reproducibility. (#7926)

**Comment by jonnymarshall** [comment]
[Fully Noded v0.3.5](https://twitter.com/fullynoded/status/1575630576866201600?s=11&t=2tTQSAqtOrUCjsHF64rTXQ)

- much improved UX when adding and exporting nodes via QR
- general improvements to the node manager
- fixes a bug that limited LND total fees collected to 100 HTLCs


**_Can't seem to find this on their [releases page](https://github.com/Fonta1n3/FullyNoded/releases)..?_**

**Comment by jonnymarshall** [comment]
[Fountain 0.5.1](https://fountainpodcasts.substack.com/p/fountain-0-5-1)

- Autoplay Queue - add episodes to your queue and enjoy continuous playback
- Apple CarPlay - iOS users can enjoy your podcasts while you’re on the road (Android Auto is in the final stages of testing and will be released very soon)
- OPML Import - Android users can now import their podcast library from other apps via OPML
- Performance Upgrades - significantly improved crashing and overheating

**Comment by jonnymarshall** [comment]
[COLDCARD Firmware 5.0.7 - 2022-10-05](https://github.com/Coldcard/firmware/blob/master/releases/ChangeLog.md#507---2022-10-05)

**Comment by kn0wmad** [comment]
[embassyOS v0.3.2](https://github.com/Start9Labs/embassy-os/releases/tag/v0.3.2)

Now with human-readable update highlights ;)

**Comment by jonnymarshall** [comment]
[Fully Noded v03.5](https://twitter.com/FullyNoded/status/1575630576866201600?s=20&t=n2rbS5VaapnR8NkWWb1Hjg)

**Comment by jonnymarshall** [comment]
### Added these for Bitcoin Optech newsletter. Both might be a bit too lightning heavy, so let me know if you wanna scrap this from the notes @nvk .

- [#219](https://bitcoinops.org/en/newsletters/2022/09/28/) - Sep 28, 2022:
    - LN fee ratecards:
        - Lisa Neigut posted to the Lightning-Dev mailing list a proposal for fee ratecards that would allow a node to advertise four tiered rates for forwarding fees.
        - Developer ZmnSCPxj described a simple way to use ratecards, “you can model a rate card as four separate channels between the same two nodes, with different costs each. If the path at the lowest cost fails, you just try another route that may have more hops but lower effective cost, or else try the same channel at a higher cost.”
        - The proposal also allows for negative fees. Negative fees could be used by merchants to incentivize others to restore inbound capacity to channels frequently used for receiving payments.
    - Bitcoin implementation designed for testing soft forks on signet:
        - Anthony Towns posted to the Bitcoin-Dev mailing list a description of a fork of Bitcoin Core he’s working on that will only operate on the default signet and which will enforce rules for soft fork proposals with high-quality specifications and implementations. This should make it simpler for users to experiment with the proposed change, including directly comparing one change to another similar change (e.g. comparing OP_CHECKTEMPLATEVERIFY to SIGHASH_ANYPREVOUT).
- [#220](https://bitcoinops.org/en/newsletters/2022/10/05/) - Oct 5, 2022:
    - Proposed new transaction relay policies designed for LN-penalty:
        - Gloria Zhao posted to the Bitcoin-Dev mailing list a proposal to allow transactions to opt-in to a modified set of transaction relay policies. Any transaction which sets its version parameter to 3 will:
            - Be replaceable while it is unconfirmed by a transaction paying a higher feerate and a higher total fee (the current main RBF rules)
            - Require all of its descendents also be v3 transactions for as long as it remains unconfirmed. Descendents violating this rule will not be relayed or mined by default
            - Be rejected if any of its v3 unconfirmed ancestors already have any other descendants in the mempool (or in a package containing this transaction)
            - Be required to be 1,000 vbytes or smaller if any of its v3 ancestors are unconfirmed
        - Together, the v3 relay and updated package relay rules are designed to allow LN commitment transactions to include only minimal fees (or potentially even zero fees) and have their actual fees paid by a child transaction, all while preventing pinning. Almost all LN nodes already use a mechanism like this, anchor outputs, but the proposed upgrade should make confirming commitment transactions simpler and more robust.
    - LN flow control:
        - Rene Pickhardt posted to the Lightning-Dev mailing list a summary of recent research he performed on using the htlc_maximum_msat parameter as a flow control valve. As previously defined in BOLT7, htlc_maximum_msat is the maximum value that a node will forward to the next hop in a particular channel for an individual payment part (HTLC). Pickhardt addresses the problem of a channel with more value flowing through it in one direction than the other direction—eventually leaving the channel without enough funds to transfer in the overused direction. He suggests that channel can be kept in balance by limiting the maximum value in the overused direction. For example, if a channel starts by allowing 1,000 sat forwards in either direction but becomes unbalanced, then try lowering the overused direction’s maximum amount per forwarded payment to 800.

**Comment by jonnymarshall** [comment]
### Updates:
- [Blockstream Green QT 1.1.4](https://github.com/Blockstream/green_qt/releases/tag/release_1.1.4)
    - Support for incremental Jade firmware update
    - Enable Request Two-Factor Reset for liquid
- [Robosats v0.2.1-alpha](https://github.com/Reckless-Satoshi/robosats/releases/tag/v0.2.1-alpha) - Sep 30, 2022
    - This patch includes the new BookTable component.
    - This is the first alpha release with an Android APK for testing.
    
###  Noteworthy:
  - [Celsius Disclosed Names and Transaction History of All Users During Bankruptcy](https://www.nobsbitcoin.com/celsius-doxxes-all-users/)
    - Court filing totals 14000 pages.
    - Data includes names, trading history, transaction times, and amounts.
    - This data can be combined with on chain data to connect self custody wallets with any Celsius user that interacted with them.
    - Celsius asked for the names of its users to be hidden from the court filings, but the judge refused saying this is a common requirement for bankruptcy cases.

**Comment by jonnymarshall** [comment]
Noteworthy:

[Arrested Tornado Cash developer to stay in jail after appeal rejected](https://www.theblock.co/post/174016/arrested-tornado-cash-developer-alexey-pertsev-appeal-rejected)
- Arrested Tornado Cash developer Alexey Pertsev’s appeal has been dismissed and he will stay in jail until at least late November, his wife tells The Block.
- The wife, Ksenia Malik, also fears all of Pertsev’s property will be seized and auctioned. 

[Grayscale unveils bitcoin mining-centered investment entity](https://www.theblock.co/post/175140/grayscale-unveils-bitcoin-mining-centered-investment-entity)
- Grayscale is launching Grayscale Digital Infrastructure Opportunities, a “private, co-investment opportunity in mining hardware that powers the bitcoin ecosystem.”
- The company is partnering with digital asset mining and staking infrastructure firm Foundry, which will manage day-to-day operations.

[European Union Announces New Sanctions Against Russia Including a "Ban" on All Russian Bitcoin Wallets](https://ec.europa.eu/commission/presscorner/detail/en/ip_22_5989)
- "The existing prohibitions on crypto assets have been tightened by banning all crypto-asset wallets, accounts, or custody services, irrespective of the amount of the wallet (previously up to €10,000 was allowed)."

**Comment by jonnymarshall** [comment]
Updates:
[Samurai v0.99.98f](https://docs.samourai.io/en/wallet/releases#v09998f)
    - New PayNym Bot & Toolbar Menu.
    - Authenticate using PayNym. Sign in to websites without an email or password, simply scan a QR code.
    - A brand new UI for both initiating and collaborating in STONEWALLx2 or Stowaway transaction.
    - New Joinbot. For a small spam prevention fee you can have JoinBot act as the second participant in a STONEWALLx2 collaborative transaction.
    - There is a small anti-spam fee in addition to the usual miner fees when using JoinBot. The service fee is set at 3.5% of the send amount or 0.01 BTC, whichever is less.
    - New 'tools' screen in the wallet activated from the new Toolbar Menu contains new UI for sweeping private keys and calculating addresses for your wallet.

**Comment by jonnymarshall** [comment]
### Noteworthy:

[bitnob launches in Kenya](https://bitnob.com/blog/announcement/bitnob-in-kenya)
    - Kenya makes it the third country the Bitnob app is available in, following Nigeria and Ghana.
    - After a one-time setup on the app users can transfer between lightning wallets and M-Pesa without any further action by the recipient. They can choose to receive bitcoin or local currency.
    - Bitnob is known for its bitcoin savings feature which helps people to automatically save in bitcoin using the dollar cost average strategy. The savings feature will give Kenyans the opportunity to save their bitcoin for 3, 6, or 12 months depending on their preferences.
    - Bitnob’s payout feature helps to make it easy for Kenyans to receive bitcoin directly into their bitcoin wallet, their USD wallet, or split between both wallets. This is quite an innovative feature giving Kenyans the freedom to choose how they would like to receive their bitcoin.
    - You can receive money from your family using Cash App or Strike in the US straight to your mobile money account.
    - You can also now send money from Kenya to Nigeria or Ghana or send money from any of these countries to Kenya.
    - Kenya is among the top 10 countries interested in cryptocurrency. According to reports, Kenya is a country interested in bitcoin, topping bitcoin search interest at 94.7%.

**Comment by jonnymarshall** [comment]
### Noteworthy:

[Swan Acquires Specter Solutions](https://www.swanbitcoin.com/swan-acquires-specter-solutions/)
    - Specter project will remain open source.
    - Swan will provide engineering support and some product direction.
    - Specter’s open source desktop project will not have any default network connections to Swan or customer identification (KYC) features.
    - Launching Specter Labs - a division of Swan focusing on open source and privacy-oriented tools that help Bitcoiners secure their holdings.
    - Will give Swan customers end-to-end services by providing deep integrations with Specter’s leading self-custody solution and other tools over time.
    -  Specter desktop client will continue to be usable with complete independence from Swan, or in conjunction with it, per the user’s preference.
