### ISSUE TITLE
Rename Episodes 1-5

### ISSUE THREAD

**Issue by jonnymarshall** [nvk/bitcoin.review.episodes#18]
- [ ] Episode 1
- [ ] Episode 2
- [ ] Episode 3
- [ ] Episode 4
- [ ] Episode 5

**Comment by jonnymarshall** [comment]
Let me know if these episode titles sound alright @nvk .

- BR001 - COLDCARD, BTC Pay Server, BlueWallet, Electrum, Sparrow, Fountain, Wasabi & MORE  ft. Odell
- BR002 - Coinkite Cards, Zeus, Zeus, Sparrow, EmbassyOS, Robosats & MORE ft. Justin Moon & Odell
- BR003 - Twitter data breach, Nunchuk, Robinhood bech32, Sphinx signer & MORE ft. Justin Moon & Odell
- BR004 - JoininBox, Tornado Cash, Swan & Casa data leaks, Square HWW & MORE ft. Justin Moon & Odell
- BR005 - Bitcoin Wallet Experts Roundtable ft. Odell, Bitstein & Pierre Rochard

**Comment by nvk** [comment]
Seems about right
