### ISSUE TITLE
Episode 03 - We continue

### ISSUE THREAD

**Issue by nvk** [nvk/bitcoin.review.episodes#3]
## Bitcoin.Review Podcast Episode 03 - We continue 

I Scratched my own itch with Episode 01, so this will keep going as my best efforts place to talk about Bitcoin Project software updates and some other commentary that I find interesting or noteworthy to me. I also would like to invite you to send Bitcoin related questions, just go to bitcoin.review and click submit story at the top right.

This week for Episode 3, our guests [Justin Moon](https://twitter.com/_JustinMoon_) and [Matt Odell](https://twitter.com/ODELL) return to help me read the list.

I should mention the overwhelming feedback is that we have failed at being boring,  so we should try to do better.

### Vulnerability Disclosures
- Twitter data breach exposes contact details for 5.4M accounts; on sale for $30k
    - twitter user names, emails, and phone numbers
    - vulnerability was disclosed in January and patched
- ActiveCampaign database leak (shiftcrypto and others affected) 
   - Name or alias, Email addressm IP address
- Blue Wallet Sends Transaction Data to Their Servers Even When Using Your Own Node
   - users need to manually disable push notifications in the app to prevent the leak

### Software Releases and Project Updates
- Nunchuk 1.9.9 https://apps.apple.com/us/app/nunchuk-bitcoin-wallet/id1563190073
   - Add support for NFC keys (Tapsigner)
   - Collaborative wallet recovery
   - Bug fixes and improvements
- [Nunchuk CKTAP C++ lib](https://github.com/nunchuk-io/tap-protocol)
- BDK 0.20.0 https://github.com/bitcoindevkit/bdk/releases/tag/v0.20.0
    - Highlights for this release include bug fixes for the ElectrumBlockchain and descriptor templates, new transactions building feature to discourage fee sniping, and new transaction signing options. Also with this release MSRV is now 1.56.1 and AddressValidator is deprecated. A big thanks to our past and latest new contributors. See below for all the details.
- COLDCARD Mk4 5.0.5 - July 20, 2022
   - Enhancement: BIP-85 derived passwords. Pick an index number, and COLDCARD will derive a deterministic, strong (136 bit) password for you. It will even type the password by emulating a USB keyboard. See new areas: Settings > Keyboard EMU and Settings > Derive Seed B85 > Passwords.
   - Documentation: added docs/bip85-passwords.md documenting new BIP-85 passwords and keyboard emulation.
   - Enhancement: BIP-85 derived values can now be exported via NFC, in addition to QR code.
   - Enhancement: Allow signing transaction where foreign UTXO(s) are missing. Only applies to cases where partial signatures are being created. Thanks to [@straylight-orbit](https://github.com/straylight-orbit)
   - Enhancement: QR Codes are now easier to scan in bright light. Thanks to [@russeree](https://github.com/russeree) for this useful fix!
   - Bugfix: order of multisig wallet registration does NOT matter.
   - Enhancement: Support import of multisig wallet from descriptor (only sortedmulti, BIP-67). Also support export of multsig wallet as descriptor.
   - Enhancement: Address explorer can show "change" addresses for standard derivation paths for both single and multisig wallet.
   - New tutorial: 2of2 multisig with 2x Coldcard signing device, and bitcoin-qt as coordinator, see docs/bitcoin-core2of2desc.md
   - Enhancement: OP_RETURN is now a known script and is displayed in ascii when possible
   - Bugfix: allow unknown scripts in HSM mode, with warning.
- Robinhood 
    - supports bech32
- Seed Tool v2 by SuperPhatArrow
    - Introducing Predictive Seed Word Input, Single Address Tool and Multisig Address Derivation 🎉
- Tor Browser v11.5 Released
    - automatic censorship detection and circumvention
    - redesigned network settings including streamlined bridge options
    - https only by default
- Joinstr: Coinjoin implementation using nostr
    - uses the nostr protocol for coordination
- bitcoinbinary.org bot updated https://github.com/coinkite/bitcoinbinary.org/pull/42

### Hiring
- Fedi mobile dev https://bitcoinerjobs.com/company/fedi
- Coinkite hiring a Python/Kivi unicorn mobile dev https://coinkite.com/careers

### Noteworthy
- Fedi update about funding https://twitter.com/fedibtc/status/1549318928954015749
- cktap-protocal in C++ by Nunchuck https://github.com/coinkite/cktap-protocol-cpp
- [Tapsigner now shipping 39 bucks](https://tapsigner.com) and SATSCARD shipping soon.
- Sphinx announces VLS signing device: The Sphinx team [announced](https://sphinx.chat/2022/06/27/a-lightning-nodes-problem-with-hats/) a hardware signing device interfacing with [Validating Lightning Signer (VLS)](https://gitlab.com/lightning-signer/docs).
- Border Wallet https://twitter.com/borderwallets/status/1550091662822711297?s=
- Keet p2p comms by Bitfinex and Theather https://twitter.com/namcios/status/1551508419097542656?s=21&t=
James O'Beirne summarizing mempool research https://github.com/jamesob/mempool.work
- Bitcoin Core updates (unreleased)
    - h/t Optech; [Bitcoin Core #24148](https://github.com/bitcoin/bitcoin/issues/24148) adds watch-only support for [output script descriptors](https://bitcoinops.org/en/topics/output-script-descriptors/) written in [miniscript](https://bitcoinops.org/en/topics/miniscript/). For example, a user can import wsh(and_v(v:pk(key_A),pk(key_B))) to begin watching for any bitcoins received to the P2WSH output corresponding to that script. A future PR is expected to add support for signing for miniscript-based descriptors.
    - h/t Optech;  [Bitcoin Core GUI #471](https://github.com/bitcoin-core/gui/issues/471) updates the GUI with the ability to restore from a wallet backup. Restoring was previously only possible either using the CLI or by copying files into particular directories.
- BitcoinTreasuries Updated with Elons booboo https://bitcointreasuries.net/
- Bitcoin Meshnets article by [L0LA L33TZ](https://bitcoinmagazine.com/authors/l0la-l33tz) https://bitcoinmagazine.com/technical/making-bitcoin-unstoppable-part-one-mesh-nets
- Gloria Zhao Added as a Bitcoin Core Maintainer, she now has commit access to the Bitcoin Core repo on github

### Bitcoin Mailing list
- 210 https://bitcoinops.org/en/newsletters/2022/07/27/
- 209 https://bitcoinops.org/en/newsletters/2022/07/20/
    - Long-term block reward ongoing discussion: NO
    
### Bitcoin Events
- Bitcoin Park Nashville Events

### Get in touch with the pod
- twitter.com/BitcoinReviewHQ
- Telegram https://t.me/BitcoinReviewPod
- Email bitcoinreview@coinkite.com

**Comment by justinmoon** [comment]
James O'Beirne summarizing mempool research https://github.com/jamesob/mempool.work

**Comment by justinmoon** [comment]
[Fedi is hiring!](https://bitcoinerjobs.com/company/fedi)

**Comment by nvk** [comment]
done

**Comment by MaxHillebrand** [comment]
nice episode.

do you have a link to joinstr?

**Comment by justinmoon** [comment]
@MaxHillebrand: this is all i've seen https://gist.github.com/1440000bytes/1c305097b070c8374cc3b91f50314a45
