### ISSUE TITLE
Facebook and LinkedIn Social links not working

### ISSUE THREAD

**Issue by jonnymarshall** [nvk/bitcoin.review.episodes#7]
On the episode page we have 2 links that seem unnecessary.

The [facebook one](https://www.facebook.com/sharer/sharer.php?u=https://btcreviews.com/podcast/2022/07/15/Episode-02.html) creates a facebook post for btcreviews.com.

The [LinkedIn one](https://www.linkedin.com/shareArticle?mini=true&title=Bitcoin.Review%20Podcast%20Ep%2002%20-%20Numero%20Dos&url=https://btcreviews.com/podcast/2022/07/15/Episode-02.html) is broken.

**Comment by nvk** [comment]
Move this issue the site repo
